# Generated by Django 2.1.5 on 2019-01-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channelid',
            new_name='channelId',
        ),
    ]
