# Generated by Django 2.1.5 on 2019-01-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20190125_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='author',
            new_name='user',
        ),
    ]
